package entity

type Claim struct {
	ID                          int     `gorm:"column:ID"`
	Number                      string  `gorm:"column:Number"`
	TransactionDate             string  `gorm:"column:TransactionDate"`
	ReferenceNumber             string  `gorm:"column:Reference_Number"`
	XFrom                       string  `gorm:"column:xFrom"`
	InsurancePartnerCode        string  `gorm:"column:InsurancePartner_Code"`
	InsuranceTypeCode           string  `gorm:"column:InsuranceType_Code"`
	InsuranceProductCode        string  `gorm:"column:InsuranceProduct_Code"`
	ClaimLetterNumber           string  `gorm:"column:ClaimLetter_Number"`
	ClaimLetterDate             string  `gorm:"column:ClaimLetter_Date"`
	DateOfIncident              string  `gorm:"column:Date_Of_Incident"`
	Submitter                   string  `gorm:"column:Submitter"`
	SubmitterEmail              string  `gorm:"column:Submitter_Email"`
	SubmitterPhone              string  `gorm:"column:Submitter_Phone"`
	Remarks                     string  `gorm:"column:Remarks"`
	Description                 string  `gorm:"column:Description"`
	Amount                      float64 `gorm:"column:Amount"`
	AmountRevision              float64 `gorm:"column:Amount_Revision"`
	SPENumber                   string  `gorm:"column:SPE_Number"`
	StatusInsurancePartner      int     `gorm:"column:Status_InsurancePartner"`
	DateInsurancePartner        string  `gorm:"column:Date_InsurancePartner"`
	FileInsurancePartner        string  `gorm:"column:File_InsurancePartner"`
	StatusClaimSubmissionLetter int     `gorm:"column:Status_ClaimSubmissionLetter"`
	StatusArrears               int     `gorm:"column:Status_Arrears"`
	Arrears                     float64 `gorm:"column:Arrears"`
	StatusPenalty               int     `gorm:"column:Status_Penalty"`
	Penalty                     float64 `gorm:"column:Penalty"`
	StatusEscalation            int     `gorm:"column:Status_Escalation"`
	Escalation                  float64 `gorm:"column:Escalation"`
	StatusBlast                 int     `gorm:"column:Status_Blast"`
	LetterOfDischargeStatus     int     `gorm:"column:LetterOfDischarge_Status"`
	LetterOfDischargeFile       string  `gorm:"column:LetterOfDischarge_File"`
	LetterOfDischargeDate       string  `gorm:"column:LetterOfDischarge_Date"`
	LetterOfDischargeSigned     string  `gorm:"column:LetterOfDischarge_Signed"`
	LetterOfDischargeSignedDate string  `gorm:"column:LetterOfDischarge_Signed_Date"`
	UPBID                       int     `gorm:"column:UPB_ID"`
	BankID                      int     `gorm:"column:Bank_ID"`
	StatusSendEmail             int     `gorm:"column:Status_SendEmail"`
	StatusPaid                  int     `gorm:"column:Status_Paid"`
	StatusDocument              int     `gorm:"column:Status_Document"`
	Approve                     int     `gorm:"column:Approve"`
	Approve2                    int     `gorm:"column:Approve2"`
	ClaimApprove                int     `gorm:"column:Claim_Approve"`
	ClaimApprove2               int     `gorm:"column:Claim_Approve2"`
	CreatedBy                   string  `gorm:"column:Created_By"`
	CreatedAt                   string  `gorm:"column:Created_At"`
	UpdatedBy                   string  `gorm:"column:Updated_By"`
	UpdatedAt                   string  `gorm:"column:Updated_At"`
	ApprovedBy                  string  `gorm:"column:Approved_By"`
	ApprovedAt                  string  `gorm:"column:Approved_At"`
	Approved2By                 string  `gorm:"column:Approved2_By"`
	Approved2At                 string  `gorm:"column:Approved2_At"`
	ClaimApprovedBy             string  `gorm:"column:Claim_Approved_By"`
	ClaimApprovedAt             string  `gorm:"column:Claim_Approved_At"`
	ClaimApproved2By            string  `gorm:"column:Claim_Approved2_By"`
	ClaimApproved2At            string  `gorm:"column:Claim_Approved2_At"`
	DeletedBy                   string  `gorm:"column:Deleted_By"`
	DeletedAt                   string  `gorm:"column:Deleted_At"`
	DeleteStatus                int     `gorm:"column:DeleteStatus"`
	BlastingAt                  string  `gorm:"column:Blasting_At"`
	Status                      string  `gorm:"column:Status"`
	BankName                    string  `gorm:"column:BankName"`
	AccountNumber               string  `gorm:"column:AccountNumber"`
	AccountName                 string  `gorm:"column:AccountName"`
	InsurancePartners           string  `gorm:"column:InsurancePartners"`
	InsurancePartnersEmail      string  `gorm:"column:InsurancePartnersEmail"`
	InsuranceType               string  `gorm:"column:InsuranceType"`
	InsuranceProducts           string  `gorm:"column:InsuranceProducts"`
	UPBCode                     string  `gorm:"column:UPB_Code"`
	UPB                         string  `gorm:"column:UPB"`
	UPBCity                     string  `gorm:"column:UPB_City"`
	Uploaded                    int     `gorm:"column:Uploaded"`
	Customer                    string  `gorm:"column:Customer"`
	Branch                      string  `gorm:"column:Branch"`
	Insured                     string  `gorm:"column:Insured"`
	InsuredAddress              string  `gorm:"column:InsuredAddress"`
	InsuredDateOfBirth          string  `gorm:"column:InsuredDateOfBirth"`
	InsuredPhoneNumber          string  `gorm:"column:InsuredPhoneNumber"`
	NoDebitur                   string  `gorm:"column:NoDebitur"`
	StartDate                   string  `gorm:"column:StartDate"`
	EndDate                     string  `gorm:"column:EndDate"`
	JUP                         float64 `gorm:"column:JUP"`
	NoPolicy                    string  `gorm:"column:NoPolicy"`
	LeaderConsorsium            string  `gorm:"column:LeaderConsorsium"`
	PaidAmount                  float64 `gorm:"column:PaidAmount"`
	PaidDate                    string  `gorm:"column:PaidDate"`
}

type ClaimDocuments struct {
	ID                         int    `gorm:"column:ID"`
	ClaimNumber                string `gorm:"column:Claims_Number"`
	DocumentID                 int    `gorm:"column:Document_ID"`
	Description                string `gorm:"column:Description"`
	Files                      string `gorm:"column:Files"`
	FilesType                  string `gorm:"column:Files_Type"`
	ReceiptNumber              string `gorm:"column:ReceiptNumber"`
	ReceiptNumberFiles         string `gorm:"column:ReceiptNumber_Files"`
	ReceiptNumberDate          string `gorm:"column:ReceiptNumber_Date"`
	RegisterNumber             string `gorm:"column:RegisterNumber"`
	StatusFiles                int    `gorm:"column:Status_Files"`
	StatusPhysicalDocument     int    `gorm:"column:Status_PhysicalDocument"`
	StatusApprove              int    `gorm:"column:Status_Approve"`
	XTimeStamp                 string `gorm:"column:xTimestamp"`
	ReasonFile                 string `gorm:"column:Reason_Files"`
	ReasonPhysicalDocument     string `gorm:"column:Reason_PhysicalDocument"`
	ReasonApprove              string `gorm:"column:Reason_Approve"`
	Document                   string `gorm:"column:Documents"`
	ClaimReceiptNumber         string `gorm:"column:ClaimsReceiptNumber"`
	ClaimReceiptNumberDate     string `gorm:"column:ClaimsReceiptNumber_Date"`
	ClaimReceiptNumberFile     string `gorm:"column:ClaimsReceiptNumber_Files"`
	StatusReceive              int    `gorm:"column:Status_Receive"`
	CreatedBy                  string `gorm:"column:Created_By"`
	DepartmentID               int    `gorm:"column:Department_ID"`
	Department                 string `gorm:"column:Department"`
	Documents                  string `gorm:"column:Documents"`
	ClaimsRegisterNumber       string `gorm:"column:ClaimsRegisterNumber"`
	StatusInsurancePartner     int    `gorm:"column:Status_InsurancePartner"`
	ReasonInsurancePartner     string `gorm:"column:Reason_InsurancePartner"`
	StatusFileInsurancePartner int    `gorm:"column:StatusFile_InsurancePartner"`
	ReasonFileInsurancePartner string `gorm:"column:ReasonFile_InsurancePartner"`
	Status                     string `gorm:"column:Status"`
}
